trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  jobs: BuildJob
  steps:
  - bash: echo "Do the Build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeploy
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: QADeploy
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to QA

