trigger:
- master

resources:
- repo: self

variables:
  tags: 35
#'$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'manifests'
    itemPattern: '**/*.yaml'
    targetPath: '$(System.ArtifactsDirectory)'
  - task: DownloadPipelineArtifact@2
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'agunueghosaworld4'
    namespace: 'default'
    manifests: 'manifests'
    containers: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
    imagePullSecrets: in28min/currency-exchange-devops:$(tags)




#image 100 tag Deploy to k8s
#Downloas
#apply - kubectl apply -f deployment.yaml

